language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python -m unittest discover
notifications:
  slack:
    secure: MpqcxZttOHuVccx/48cOSf4dafMRBHwrgeONI12oogD73mYiaDhJcmvEUgeNYtxy1y3Kw00QCaflpc6DQJ2aHMoef49dqtLV9G+QTe9JmsKECxiAs7pScaveeR7GN0r6CMyURbDygxZBN+Zj649J0SwcjtqqpPTj/VbyXJ7ApaiQgfBhRN/u+eR2CHGPunBwB5YonffN3PY1HmzNKg0+9gpRno8X4Q9ZXlYCTNEXjGNafgf1lGfXXIft93V1PSWAb7uUhPtxzwiln7EGkw/VG6dKfOOzaWzi6CRjU6AEIqQy5TNA9olYXQITndoSTJ6KP5Avrgjh/v3NMpdPj1v0C7RTN3EE4Gvh5t6iK0wAWZRst5JMadHEd+rKAq8LToh2Xl4EPuj+U8B+RvsoYd5PBwZC0uE7wy1pErvKf29YRkPVv4vkET4k1UuSnkNY55BUSKpRt0Ks7R0oPeil3HOORH/jfTGAUewvnAogY14gWyAc9oDt8Zy1YqOsjbJYa476MhovEdAa8TZkMgRAn2JvVEiEF2BdHHsJgPgWcz4YndhpikoM2043Io28+MPyxW8PyHV1HIomHUC09uixiIHWQAzuDPvToLVJwxJ2ABOidXoC6/Sse19MP2QQPXM+wrIndBjDb13N/CK/NQg70n2zGxYF5CLbitvUah+CRf1g8zU=
